title: Sharmista Kothavadla
logo: https://github.com/Sharmistaroy/Portfolio-Data-science/commit/19fd0a70d9fe2853f25c80477bd73b9c6d390435#r142734134
description: text below image
show_downloads: true
theme: jekyll-theme-minimal
